# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
           #Pull down libdl.so dependency
          - apt-get update && apt-get install -y libc6-dev
           #Build project, sample, and run unit tests
          - export PROJECT_NAME=AssimpNet
          - export SAMPLE_NAME=AssimpNet.Sample
          - export TEST_NAME=AssimpNet.Test
          - export CONFIG=Release
          - export FRAMEWORK-netstandard1.3
          - dotnet restore
          - dotnet build $PROJECT_NAME --framework $FRAMEWORK --configuration $CONFIG
          - dotnet build $SAMPLE_NAME --configuration $CONFIG
          - dotnet test $TEST_NAME --configuration $CONFIG
