name: .NET Desktop CI

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  Linux_x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Build Project (.Net Standard, Release)
        run: dotnet build AssimpNet -f netstandard1.3 -c Release
      - name: Run Tests (.Net Core App, Release)
        run: dotnet test AssimpNet.Test -f netcoreapp3.1 -c Release

  MacOS_x64:
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Build Project (.Net Standard, Release)
        run: dotnet build AssimpNet -f netstandard1.3 -c Release
      - name: Run Tests (.Net Core App, Release)
        run: dotnet test AssimpNet.Test -f netcoreapp3.1 -c Release

  Windows_x64:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build Project (.Net Standard, Release)
        run: dotnet build AssimpNet -f netstandard1.3 -c Release
      - name: Build Project (.Net Framework 4, Debug)
        run: dotnet build AssimpNet -f net4 -c Debug
      - name: Run Tests (.Net Core App, Release, x64)
        run: dotnet test AssimpNet.Test -c Release -f netcoreapp3.1 -- RunConfiguration.TargetPlatform=x64
      - name: Run Tests (.Net Framework 4.8, Debug, x86)
        run: dotnet test AssimpNet.Test -c Debug -f net48 -- RunConfiguration.TargetPlatform=x86

  Build_Artifacts:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install .Net Framework 3.5
        run: Enable-WindowsOptionalFeature -Online -FeatureName "NetFx3"
        shell: pwsh
      - name: Restore Nuget Dependencies
        run: dotnet restore AssimpNet/AssimpNet.csproj
      - name: Build Nuget Packages
        run: msbuild AssimpNet/AssimpNet.csproj /p:Configuration=Release
      - name: Zip Unity Plugin
        run: |
          New-Item -ItemType Directory -Force -Path AssimpNet/bin/Release/UnityPlugin
          Compress-Archive -Path AssimpNet/bin/Release/UnityPlugin -DestinationPath AssimpNet/bin/Release/UnityPlugin.zip -Force
        shell: pwsh
      - name: Gather Artifacts
        run: |
          New-Item -ItemType Directory -Force -Path _artifacts
          Copy-Item -Path AssimpNet/bin/Release/*.{nupkg,snupkg,zip} -Destination _artifacts -Force
        shell: pwsh
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: _artifacts
